---
driver:
  name: vagrant
  customize:
    memory: 768

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ["private_network", {ip: "192.168.12.31"}]
  - name: ubuntu-14.04
    driver:
      network:
        - ["private_network", {ip: "192.168.12.32"}]
  - name: ubuntu-14.10
    driver:
      network:
        - ["private_network", {ip: "192.168.12.33"}]
  - name: centos-6.6
    driver:
      network:
        - ["private_network", {ip: "192.168.12.34"}]
  - name: centos-7.1
    driver:
      network:
        - ["private_network", {ip: "192.168.12.35"}]
  - name: centos-5.11
    driver:
      network:
        - ["private_network", {ip: "192.168.12.36"}]
  - name: fedora-20
    driver:
      network:
        - ["private_network", {ip: "192.168.12.37"}]
  - name: fedora-21
    driver:
      network:
        - ["private_network", {ip: "192.168.12.38"}]

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[guru-sensu::all_in_one]
    attributes:
